//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public System.DateTime SaleDate { get; set; }
        public decimal PricePaid { get; set; }
        public string RecordID { get; set; }
        public int CustNum { get; set; }
        public int NumPurchased { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Record Record { get; set; }
    }
}
